### ISSUE TITLE
Peer To Peer Review - 12/12/2019

### ISSUE THREAD

**Issue by SofiBretz** [CornetS28/book-management#5]
## Enhancements:
- In `BooksForm.js`, check if it's necessary to use `...book` to update the state in the method `handleChange`.
- Call the `handleBookSubmit` from the `onSubmit` event listener in the form tag, and change the button type to `submit`.
- Please try to follow the template for the readme file :) here is the link: `https://github.com/microverseinc/readme-template` 
## Further Comments
- Good job! 

> Reviewed with :heart: by Team 35: The Deadpools

**Comment by cornets28** [comment]
Thanks for your feedback. All the changes were made in the 5th milestone and merged to the development branch. To see those changes, Please, view the 5th milestone or the master branch.

Again, I appreciated your feedback!
